#!/bin/sh

function smart_pwd {
	# Original code may be https://gist.github.com/ricardochimal/293517
	local pwdmaxlen=$(( $COLUMNS-35 ))
	local trunc_symbol=".."
	local dir=${PWD##*/}
	local tmp=""
	pwdmaxlen=$(( ( pwdmaxlen < ${#dir} ) ? ${#dir} : pwdmaxlen ))
	if [[ $PWD == $HOME* ]]; then
		SMART_PWD="~${PWD#${HOME}}"
	else
		SMART_PWD="$PWD"
	fi
	# set title
	printf "\033]0;%s\007" "${USER}@${HOSTNAME}: ${SMART_PWD}"

	SMART_PWD_TRUNC=""
	local pwdoffset=$(( ${#SMART_PWD} - pwdmaxlen ))
	if [ ${pwdoffset} -gt "0" ]
	then
		tmp=${SMART_PWD:$pwdoffset:$pwdmaxlen}
		tmp=${trunc_symbol}/${tmp#*/}
		if [ "${#tmp}" -lt "${#SMART_PWD}" ]; then
			SMART_PWD_TRUNC="${trunc_symbol}"
			SMART_PWD="${tmp:${#trunc_symbol}}"
		fi
	fi

	test x"$*" = x || "$@"
}

function fancyprompt {
	PROMPT_COMMAND="smart_pwd ${PROMPT_COMMAND//smart_pwd /}"

	theme_${ps1_theme}
	local timeps='\[\e[$[COLUMNS-19]C\]'"\\[$(bgcolor ${TIME_BG})$(fgcolor ${TIME_FG})"'\D{%a %b %d %T}\r'"$(resetcolor)\\]"
	local uahps="\\[$(bgcolor ${USERNAME_BG})$(fgcolor ${USERNAME_FG})\\]\\u\\[$(fgcolor ${ATMARK_FG})\\]@\\[$(fgcolor ${USERNAME_FG})\\]\\h"
	local pwdps="\\[$(bgcolor ${PWD_BG})$(fgcolor ${PWD_TRUNKMARK_FG})\\]\${SMART_PWD_TRUNC}\\[$(fgcolor ${PWD_FG})\\]\${SMART_PWD}\\[$(resetcolor)\\]"
	local extraps="\\[$(fgcolor ${EXTRA_FG})\\]${EXTRA_TXT}"
	local statusps="\\[$(fgcolor ${STATUS_FG})\\]\${STATUS_TXT}"
	local dollerps="\\[$(fgcolor ${DOLLAR_FG})\\]\\\$\\[$(resetcolor)\\] "
	PS1="${timeps}${uahps} ${pwdps}\n${extraps}${statusps}${dollerps}"
}


