#!/bin/sh

function smart_pwd {
	local pwdmaxlen=$(( $COLUMNS-35 ))
	local trunc_symbol=".."
	local dir=${PWD##*/}
	local tmp=""
	pwdmaxlen=$(( ( pwdmaxlen < ${#dir} ) ? ${#dir} : pwdmaxlen ))
	NEW_PWD="${PWD/#$HOME/~}"
	NEW_PWD_TRUNC=""
	local pwdoffset=$(( ${#NEW_PWD} - pwdmaxlen ))
	if [ ${pwdoffset} -gt "0" ]
	then
		tmp=${NEW_PWD:$pwdoffset:$pwdmaxlen}
		tmp=${trunc_symbol}/${tmp#*/}
		if [ "${#tmp}" -lt "${#NEW_PWD}" ]; then
			NEW_PWD_TRUNC="${trunc_symbol}"
			NEW_PWD="${tmp:${#trunc_symbol}}"
		fi
	fi
}

function fancyprompt {
	PROMPT_COMMAND="smart_pwd"

	theme_${ps1_theme}
	if [ ! \( -v TIME_BG -a -v TIME_FG -a -v USERNAME_BG -a -v USERNAME_FG -a -v ATMARK_FG -a -v PWD_BG -a -v PWD_TRUNKMARK_FG -a -v PWD_FG -a -v EXTRA_FG -a -v EXTRA_TXT -a -v DOLLAR_FG \) ]; then
		echo "Theme seems to be partially defined" >&2
	fi
	PS1='\[\e[$[COLUMNS-19]C'"$(bgcolor ${TIME_BG})$(fgcolor ${TIME_FG})"'$(LC_ALL=C date +"%a %b %2d %T")\r'"$(resetcolor)\\]\\[$(bgcolor ${USERNAME_BG})$(fgcolor ${USERNAME_FG})\\]\u\\[$(fgcolor ${ATMARK_FG})\\]@\\[$(fgcolor ${USERNAME_FG})\\]\h \\[$(bgcolor ${PWD_BG})$(fgcolor ${PWD_TRUNKMARK_FG})\\]\${NEW_PWD_TRUNC}\\[$(fgcolor ${PWD_FG})\\]\${NEW_PWD}\\[$(resetcolor)\\] \\[$(fgcolor ${EXTRA_FG})\\]\n${EXTRA_TXT}\\[$(fgcolor ${DOLLAR_FG})\\]\\\$\\[$(resetcolor)\\] "
}

function dullprompt {
	PROMPT_COMMAND=""
	export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '
}
case "$TERM" in
	xterm-color|xterm-256color|rxvt*|screen-256color)
		___COLOR_MODE=256
		fancyprompt
		;;
	*)
		___COLOR_MODE=16
		dullprompt
		;;
esac


