#!/bin/sh
if [[ "${OSTYPE}" == darwin* ]]; then
	_debug -n "Git Prompt Loading..."
	source /usr/share/git-core/git-prompt.sh
	_debug "ok"
	_debug -n "Git Completion Loading..."
	source /usr/share/git-core/git-completion.bash
	_debug "ok"
fi
