#!/bin/sh
[[ -f /etc/profile.d/bash-completion.sh ]] || return

source /etc/profile.d/bash-completion.sh

function have {
	which $1 >/dev/null 2>&1 && return 1
	return 0
}


#for i in ${HOME}/.bash_completion.d/*; do
#	source $i 
#done
