#!/bin/sh
[[ -f /etc/profile.d/bash-completion.sh ]] || return

source /etc/profile.d/bash-completion.sh

# for git_prompt
source /usr/share/git/git-prompt.sh

#for i in ${HOME}/.bash_completion.d/*; do
#	source $i 
#done
