#!/bin/sh
_eclipse() {
	local cur
	cur=${COMP_WORDS[COMP_CWORD]}
	if (( $COMP_CWORD <= 1 )); then
		COMPREPLY=( $(cd ${HOME}/workspace; compgen -W "$(find */.eclipse -maxdepth 0 | cut -d'/' -f1)" -- ${cur}) )
	else
		COMPREPLY=( $(compgen -W "-clean _" -- ${cur}) )
	fi
	return 0;
}
complete -F _eclipse eclipse
