#!/bin/bash

_venv_help() {
	cat <<EOF
venv [activate [<envdir>]]
venv create <envdir>
venv deactivate
venv help
EOF
}

_venv_activate() {
	local env_name="${1:-venv}"
	if [ ! -d "${env_name}" ]; then
		echo "not dir: ${env_name}" >&2
		return 1
	fi
	if [ ! -e "${env_name}/bin/activate" ]; then
		echo "no file: ${env_name}/bin/activate" >&2
		return 1
	fi

	# backup $PS1
	local _bak_ps1="${PS1}"
	source "${env_name}/bin/activate"
	PS1="${_bak_ps1}"
	local _env_base="$(basename "${env_name}")"
	if [ "${_env_base}" = "venv" ]; then
		STATUS_TXT="(venv)"
	else
		STATUS_TXT="(venv:$(basename ${env_name}))"
	fi
}

_venv_deactivate() {
	deactivate
	STATUS_TXT=
}

_venv_create() {
	python -m venv "$@"
}

venv() {
	if ${1+false} :; then
		if [ -d venv ]; then
			if _venv_activate venv; then
				return 0
			fi
		fi
		_venv_help >&2
		return 1
	fi

	local subcmd="$1"
	shift
	case "${subcmd}" in
		activate|a|in)
			_venv_activate "$@";;
		create|c)
			_venv_create "$@";;
		deactivate|d|out)
			_venv_deactivate;;
		*)
			_venv_help;;
	esac
}
