#!/bin/sh

if [ -z "${DISPLAY}" ];then
	export LANG="en_US.UTF-8"
else
	export LANG="ja_JP.UTF-8"
fi
export LC_TIME="en_US.UTF-8"

alias ls='ls --color=auto'
alias less='less -R'
alias pemerge='sudo emerge --jobs=3 --load-average=2.3'
alias rm='rm -i'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias sort='LC_ALL=C sort'
alias by='byobu'
# export PS1='\[\033[01;32m\]\u@gentoo\[\033[01;34m\] \w \$\[\033[00m\] '
export PATH="${HOME}/bin:${PATH}:/sbin:/usr/sbin"
export PAGER='/usr/bin/less -R'
export EDITOR='/usr/bin/vim'
#export MAIL='.maildir/'
export HISTSIZE=30000
export HISTFILESIZE=400000
export HISTCONTROL='ignoreboth'
export HISTIGNORE="fg*:bg*:history*"


# 履歴ファイルを上書きではなく追加する。
# 複数のホストで同時にログインすることがあるので、上書きすると危険だ。
shopt -s histappend
# "!"をつかって履歴上のコマンドを実行するとき、
# 実行するまえに必ず展開結果を確認できるようにする。
shopt -s histverify
# 履歴の置換に失敗したときやり直せるようにする。
shopt -s histreedit
# 端末の画面サイズを自動認識。
shopt -s checkwinsize
# なにも入力してないときはコマンド名を補完しない。
# (メチャクチャ候補が多いので。)
shopt -s no_empty_cmd_completion

stty kill undef
stty stop undef

export GPG_TTY=`tty`
