#!/bin/sh
if [[ $- = *i* ]]; then
	if [ -n "$1" ];then
		dir=$1
	else
		dir=${HOME}/.bashrc.d
	fi

	for i in ${dir}/*_*; do
		if ! test -x "$i"; then
			printf "\033[KLoading %s..." "$i"
			if source "$i"; then
				printf " ok.\r"
			else
				echo " failed."
			fi
		fi
	done

	printf "\033[K.bashrc loaded"
fi
