#!/bin/sh

function __turenar_bashrc_set_rcpath() {
	if [ -n "$1" ];then
		__turenar_bashrc_rcpath="$1"
	else
		__turenar_bashrc_rcpath="$(dirname "$0")"
	fi
}

function __turenar_bashrc_loader() {
	local dir i mingw
	if [[ "$(uname)" == MINGW* ]]; then
		mingw=y
	else
		mingw=
	fi

	for dir in ${__turenar_bashrc_rcpath}; do
		for i in "${dir}"/*_*; do
			if ! source "$i"; then
				echo "Failed to load $i."
			fi
		done
	done

	printf "\033[K.bashrc loaded\n"
}

if [[ $- = *i* ]]; then
	__turenar_bashrc_set_rcpath "$@"
	__turenar_bashrc_loader "$@"
fi
